services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: keycloak-server
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8080:8080"
    networks:
      - fall-insurance-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8081:8080"
    environment:
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak-server:8080/realms/fall-insurance
    depends_on:
      - keycloak
    networks:
      - fall-insurance-net

networks:
  fall-insurance-net:
    driver: bridge